baseURL = 'https://www.compandsave.com/blog/'
title = 'Compandsave Blog - Everything about Ink and Printer'
theme = 'casBlog'
publishDir = 'blog'
uglyURLs = true
summaryLength= 25
pagination.pagerSize = 9
disqusShortname = 'compandsave-blog'

[params]
    name= 'CompAndSave'
    description = 'CompAndSave.com: Compare Prices and Save on Ink & Toner!'
    dateFormat = "Jan 02, 2006"

[taxonomies]
	authors = "authors"
	tags = "tags"

[outputs]
    home = ["html", "rss"]
    page = ["html"]
    section = ["html"]
    taxonomy = ["html"]
    term = ["html"]

[outputFormats]
    [outputFormats.html]
        ugly = true